# -*- coding: utf-8 -*-
"""Afame_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoTDVK2mTIJVRvAiQHIUKSCiWwHapRpF
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
sales_data = pd.read_excel("ECOMM DATA.xlsx")

# Data exploration and preprocessing
print(sales_data.info())
print(sales_data.describe())

# 1. Total Sales
total_sales = sales_data['Sales'].sum()
print("Total Sales:", total_sales)

# 2. Sales Trends Over Time
# Convert 'Order Date' to datetime format
sales_data['Order Date'] = pd.to_datetime(sales_data['Order Date'])

# Extract year and month from 'Order Date'
sales_data['YearMonth'] = sales_data['Order Date'].dt.to_period('M')

# Group by year-month and sum sales
monthly_sales = sales_data.groupby('YearMonth')['Sales'].sum()

# Plot sales trends over time
plt.figure(figsize=(12, 6))
monthly_sales.plot(kind='line', marker='o')
plt.title('Monthly Sales Trends')
plt.xlabel('Year-Month')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# 3. Best-Selling Products
best_selling_products = sales_data.groupby('Product Name')['Quantity'].sum().sort_values(ascending=False).head(10)
print("Top 10 Best-Selling Products:")
print(best_selling_products)

# Plot best-selling products
plt.figure(figsize=(10, 6))
best_selling_products.plot(kind='bar')
plt.title('Top 10 Best-Selling Products')
plt.xlabel('Product Name')
plt.ylabel('Quantity Sold')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 4. Revenue Indicators
# Average revenue per order
avg_revenue_per_order = sales_data.groupby('Order ID')['Sales'].sum().mean()
print("Average Revenue per Order:", avg_revenue_per_order)

# Average revenue per product
avg_revenue_per_product = sales_data.groupby('Product Name')['Sales'].mean().sort_values(ascending=False).head(10)
print("\nTop 10 Products by Average Revenue:")
print(avg_revenue_per_product)

# Plot average revenue per product
plt.figure(figsize=(10, 6))
avg_revenue_per_product.plot(kind='bar')
plt.title('Top 10 Products by Average Revenue')
plt.xlabel('Product Name')
plt.ylabel('Average Revenue')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()